# Generated by Django 4.0.4 on 2022-11-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='solutions',
            new_name='notes',
        ),
    ]
