# Generated by Django 4.0.4 on 2022-11-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_solutions_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
