# Generated by Django 4.0.4 on 2022-11-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='likes',
        ),
    ]
