# Generated by Django 4.0.4 on 2022-11-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_notes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
