# Generated by Django 4.0.4 on 2022-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_notes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='dislike',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notes',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
