# Generated by Django 4.0.4 on 2022-11-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_notes_dislike_alter_notes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='image',
            field=models.FileField(blank=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
