# Generated by Django 4.0.4 on 2022-11-30 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_comment', models.CharField(max_length=500)),
                ('note', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.notes', verbose_name='Название товара')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
